### ISSUE TITLE
How to use the repo and see the test from web browser?

### ISSUE THREAD

**Issue by zydjohnHotmail** [atata-framework/atata-samples#3]
Hello:
I found this repo seems to be interesting, so I want to take a look.
I downloaded the code in zip format, unzip it, and copy to a location in my Windows 10 PC.
I opened the folder in “atata-samples-master\SampleApp.UITests”, and opened SampleApp.UITests.sln  with Visual Studio 2022.
I can see the project structure, it looks nice, but when I run it in debug mode, the solution simply finishes without showing any web browser actions.
I can see the result in console window like this:
C:\Program Files\dotnet\dotnet.exe (process 42792) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

I tried to set a debug break point at: 
public class UITestFixture
[SetUp]
public void SetUp()
{
AtataContext.Configure().Build();
}
But the break point was not hit by the program.
Any suggestions on how I can run the test and see the web page actions, like: create a new user, and login.
Thanks,

**Comment by YevgeniyShunevych** [comment]
Hi,

You need to use [Test Explorer](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2022) in order to run any tests in Visual Studio.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I can run the test now.
But I have yet another question: if the test runs well, how I can build a test as an .EXE like an ordinary application (like notepad.exe), then I can launch it by click on its icon or launch it from command line.
Please advise!
Thanks,

**Comment by YevgeniyShunevych** [comment]
I have never thought of something like that in .NET. I usually use `dotnet test` command (which is used in CI pipelines as well) to run tests outside of Visual Studio. You can pass filter there to run one or few particular tests. But anyway it happens rare, as I am comfortable with Visual Studio. You can try to google for some tool for .NET that can make application for tests.
