### ISSUE TITLE
Error when trying to start test on Microsoft Edge browser

### ISSUE THREAD

**Issue by ostap024** [atata-framework/atata-samples#4]
I'm getting error when I'm trying to run tests on Microsoft Edge. 
![image](https://user-images.githubusercontent.com/40698896/188466750-31a86103-5fba-4321-93f4-2e754fcaa2d9.png)
I have a driver in this folder, but the name is different 
![image](https://user-images.githubusercontent.com/40698896/188466878-afaeab5c-97d5-4563-a92f-f1e1818ccdcf.png)
How can I fix this error?

UPD: When I renamed the driver in a folder on MicrosoftWebDriver.exe, it's fix the problem, but is any other way how to do it from code?

**Comment by YevgeniyShunevych** [comment]
What are the versions of Atata, Selenium.WebDriver and Atata.WebDriverSetup packages that you use? I see no problems with the latest versions.

**Comment by ostap024** [comment]
Atata - 1.14.0
Selenium.WebDriver - 3.141.0
Atata.WebDriverSetup - 1.2.1
Microsoft Edge - 105.0.1343.27

**Comment by YevgeniyShunevych** [comment]
Yes, there is such a problem with Selenium.WebDriver v3 and EdgeDriver. The best solution is just to use Selenium.WebDriver v4 together with Atata v2. That will solve the issue. But please consider [Migrating to Atata v2](https://atata.io/tutorials/migrating-to-atata-v2/) article, as there were breaking changes in Atata v2 and WebDriver v4.

If you want to stick with Atata v1.14.0, you can, as you mentioned, to rename or copy driver exe file. I don't know the better option here.

```cs
AtataContext.GlobalConfiguration.AutoSetUpDriverToUse();

string driverDirectoryPath = Environment.GetEnvironmentVariable("EdgeDriver");
File.Copy(
    Path.Combine(driverDirectoryPath, "msedgedriver.exe"),
    Path.Combine(driverDirectoryPath, "MicrosoftWebDriver.exe"),
    true);
```
